name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build documentation
        run: cargo doc --no-deps
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: Fluid-Dynamics-Group/hdf5-derive-docs
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
